# name: ❄️ Nix Checks
# on:
#   pull_request:
#   push:
#     branches: [main, master]
# jobs:
#   nixfmt:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - run: nix-env -iA nixpkgs.nixfmt
#       - run: nixfmt $(find . -name '*.nix')
