name: Pre-commit Checks
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  sqlfluff-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install sqlfluff
      - run: sqlfluff lint sql/
  sqlfluff-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install sqlfluff
      - run: sqlfluff fix --force --check sql/
