name: Pre-commit Checks
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install yamllint
      - run: yamllint .
  yamlfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamlfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/google/yamlfmt/releases/latest/download/yamlfmt_linux_amd64 -O /usr/local/bin/yamlfmt
          chmod +x /usr/local/bin/yamlfmt
      - name: Run yamlfmt
        run: yamlfmt -lint $(find . -name '*.yaml' -o -name '*.yml')
