name: Pre-commit Checks
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install yamllint
      - run: yamllint .
  yamlfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamlfmt
        run: sudo snap install yamlfmt
      - name: Run yamlfmt
        run:  |
          for f in $(find . -name '*.yaml' -o -name '*.yml'); do
            if grep -q '[^[:space:]#]' "$f"; then
              yamlfmt "$f"
            fi
          done
